#!/bin/sh

. /usr/share/openlist2/functions.sh
openlist2_migrate_config || exit 1

[ -f "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@openlist2[-1]
	add ucitrack openlist2
	set ucitrack.@openlist2[-1].init=openlist2
	commit ucitrack
EOF
}

rm -rf /tmp/luci-*
exit 0
